apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: code-review-pg
    url: localhost:5432
    database: code_review
    user: postgres
    secureJsonData:
      password: "Kartik@0026"
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
